### ISSUE TITLE
[Design] 행사 상세보기 UI 구현

### ISSUE THREAD

**Issue by taipaise** [Kerdy-iOS/Kerdy-iOS#38]
## 💡 Issue

- 행사 상세 정보 UI 구현
## 📝  Todo
- [ ] 행사 상세 정보 UI 구현 !
- [ ] 게시판 UI 구현!
- [ ] 함께해요 UI 구현!
