### ISSUE TITLE
[Feat] 초기 설정 로직 구현

### ISSUE THREAD

**Issue by ekrud99** [Kerdy-iOS/Kerdy-iOS#44]
## 💡 Issue

초기 설정 로직 구현
## 📝  Todo
- [x] 카테고리 받아오기
- [x] 교육 이력 받아오기
- [x] 동아리 받아오기
- [x] 이름 설정
- [x] 관심 있는 카테고리 설정
- [x] 교육 이력 설정
- [x] 동아리 활동 설정
