### ISSUE TITLE
[Feat] 태그 알림 UI 로직 구현

### ISSUE THREAD

**Issue by jeongdung-eo** [Kerdy-iOS/Kerdy-iOS#45]
## 💡 Issue
- 태그 알림 UI 로직 구현을 위한 이슈
## 📝  Todo
- [x] 태그 알림 UI 수정 
- [ ] 푸쉬 알림 구현 
- [x] 태그 알림 로직 구현
