### ISSUE TITLE
[Feat] 네트워크 세팅 및 GitHub 로그인 구현

### ISSUE THREAD

**Issue by jeongdung-eo** [Kerdy-iOS/Kerdy-iOS#46]
## 💡 Issue
- 깃헙 로그인 구현을 위한 이슈
## 📝  Todo
- [x] 로그인 UI 구현 
- [x] 깃헙 로그인 로직 구현
- [x] keychain
- [x] 네트워크 세팅
- [x] 자동 로그인 구현
